extends: airbnb-base
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 8
  sourceType: module
globals:
  # These globals are for specs. ESLint doesn't have a way to just whitelist
  # for .spec.js only.
  sails: true
  User: false
  Student: false
rules:
  max-len:
    - error
    - 80
  no-console: error
  no-underscore-dangle: error